### ISSUE TITLE
Color Customization

### ISSUE THREAD

**Issue by kazumaxneo** [EbmeyerSt/GEnView#7]
Hello.
Is it possible to customize the colors in the visualization results?
I am interested in examining ORFs that are conserved only in certain species.
At this time, if I query the sequence of an ORF conserved only in a particular species, species for which that ORF is not conserved will be excluded.
Therefore, I would like to proceed by using evolutionarily conserved ORFs adjacent to the ORF of my interest. 
So, I am happy if therre are the option to turn off the red color of the ORFs in the query, as it is not the ORFs  that I am interested in.

**Comment by EbmeyerSt** [comment]
Hey, 

At the moment there is no option to customize colors, but it should be relatively straight forward to implement. I'll look into it as soon as I have a bit of time and let you know once it is implemented!

/Stefan

**Comment by kazumaxneo** [comment]
Thank you!

**Comment by EbmeyerSt** [comment]
Hey, I have now released the update, and you can customize the colors in your visualization using the --custom_colors flag with genview-visualize!
